- name: Deploy Docker Images to Docker Hub
  hosts: localhost
  tasks:
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Push Backend Image
      community.docker.docker_image:
        name: maina19/fullstack-backend
        push: true
    - name: Push Frontend Image
      community.docker.docker_image:
       name: maina19/fullstack-frontend
       push: true