- name: Deploy Docker Images to Docker Hub
  hosts: localhost
  tasks:
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env','DOCKER_HUB_USER') }}"
        password: "{{ lookup('env','DOCKER_HUB_PASS') }}"
    - name: Push Backend Image
      community.docker.docker_image:
        name: yourdockerhub/fullstack-backend
        push: true
    - name: Push Frontend Image
      community.docker.docker_image:
       name: yourdockerhub/fullstack-frontend
       push: true